# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java sasas
name: $(majorMinorVersion).$(semanticVersion)
trigger:
- master

pool:
  vmImage: windows-latest
variables:
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  PackageVersion : $(Build.BuildNumber)
steps:
- script: echo '$(Build.BuildNumber)'
- task: PowerShell@2
  #env:
   # BP: $(Build.ArtifactStagingDirectory)
  inputs:
    targetType: 'inline'
    script: | 
       $BaseVersionNo = "Policy Base Version No. : 7.1.0.2430 ~"
       $versionNo = "Policy Customization Version No. : $(build.buildNumber)"
       echo $versionNo
       echo $(Build.ArtifactStagingDirectory)
       Set-Content -Path $(Build.Repository.LocalPath)/PolicyBuildVersion.txt -Value $BaseVersionNo, $versionNo
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)/test.ps1'
    arguments: '$(Build.SourcesDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:/a/1/s/logs.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    configuration: 
    versioningScheme: byEnvVar
    versionEnvVar: PackageVersion
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '0d7b1a23-6772-4230-bae1-cdafd6a90f65'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.artifactStagingDirectory)'
    ArtifactName: 'nuspec'
    publishLocation: 'Container'
    
