# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java sasas

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo '$(Build.BuildNumber)'
- task: Maven@3
  inputs:
    mavenPomFile: 'myTestProj/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: Maven@3
  inputs:
    mavenPomFile: 'myTestProj/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)/test.ps1'
    arguments: '$(Build.SourcesDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:/a/1/s/logs.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
