# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'myTestProj/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/myTestProj/target/myTestProj-0.0.2-SNAPSHOT.war'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/myTestProj/target/myTestProj-0.0.2-SNAPSHOT.war'
    MachineNames: '172.18.51.167'
    AdminUserName: 'anurudra.goel@coforgetech.com'
    AdminPassword: 'Shivani@2012'
    TargetPath: 'E:\test'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(d04d8db4-6ff6-4f03-bf38-98a64ea60a27)'
    appType: 'webApp'
    WebAppName: 'myTestProj-0.0.2-SNAPSHOT'
    packageForLinux: '$(Build.SourcesDirectory)/myTestProj/target/myTestProj-0.0.2-SNAPSHOT.war'